import type { Chamber } from './model.ts';

export const advancedLevels: Chamber[] = [
  {
    title: 'Keep the other half',
    lesson: 'Carry a mineral through each refit to complete the relay.',
    hint: 'Preserve the mineral that still pulls the core after each release.',
    hints: ['Which mineral must arrive at the next dock in your capsule?', 'Each refit has one fresh mineral. Your remaining mineral becomes the next switch delivery.', 'Launch Skyglass + Sunstone; release Skyglass toward A and ride right. Keep Sunstone, add Ironroot, then release Sunstone toward B and descend. Keep Ironroot, add Mossjade, then release Ironroot toward C and ride left. Keep Mossjade, add Skyglass, then release Mossjade toward D and rise to the receiver.'],
    docks: [
      { x: 285, y: 270, r: 35, name: 'Launch', minerals: ['north', 'east'] },
      { x: 690, y: 155, r: 40, name: 'East', minerals: ['south'] },
      { x: 805, y: 315, r: 40, name: 'Low', minerals: ['west'] },
      { x: 265, y: 430, r: 40, name: 'West', minerals: ['north'] },
      { x: 150, y: 105, r: 40, name: 'Receiver', exit: true },
    ],
    walls: [{ x: 400, y: 255, w: 245, h: 85 }],
    switches: [
      { id: 'a', mineral: 'north', rect: { x: 345, y: 80, w: 130, h: 20 } },
      { id: 'b', mineral: 'east', rect: { x: 910, y: 210, w: 20, h: 120 }, requires: ['a'] },
      { id: 'c', mineral: 'south', rect: { x: 625, y: 480, w: 145, h: 20 }, requires: ['b'] },
      { id: 'd', mineral: 'west', rect: { x: 35, y: 270, w: 20, h: 120 }, requires: ['c'] },
    ],
    gates: [
      { id: 'east', rect: { x: 540, y: 110, w: 18, h: 110 }, requires: ['a'] },
      { id: 'west', rect: { x: 555, y: 375, w: 18, h: 115 }, requires: ['b'] },
      { id: 'north', rect: { x: 100, y: 275, w: 105, h: 18 }, requires: ['c'] },
      { id: 'receiver', rect: { x: 100, y: 175, w: 105, h: 18 }, requires: ['d'] },
    ],
  },
  {
    title: 'One more passenger',
    lesson: 'The final refit still needs the mineral you bring with you.',
    hint: 'Keep Skyglass all the way to the final refit.',
    hints: ['After the last switch, which mineral will the receiver approach need?', 'The last refit supplies Sunstone, so arrive carrying Skyglass. The circuit is also a delivery chain.', 'Release Skyglass toward A, Sunstone toward B, Ironroot toward C, then Mossjade toward D, adding the fresh mineral at each refit. Keep Skyglass when you reach High. Add Sunstone and take the diagonal to the receiver.'],
    docks: [
      { x: 320, y: 245, r: 35, name: 'Launch', minerals: ['north', 'east'] },
      { x: 710, y: 130, r: 40, name: 'East', minerals: ['south'] },
      { x: 825, y: 310, r: 40, name: 'Low', minerals: ['west'] },
      { x: 275, y: 430, r: 40, name: 'West', minerals: ['north'] },
      { x: 160, y: 215, r: 40, name: 'High', minerals: ['east'] },
      { x: 300, y: 75, r: 40, name: 'Receiver', exit: true },
    ],
    walls: [{ x: 435, y: 250, w: 220, h: 90 }],
    switches: [
      { id: 'a', mineral: 'north', rect: { x: 370, y: 45, w: 145, h: 20 } },
      { id: 'b', mineral: 'east', rect: { x: 865, y: 180, w: 20, h: 120 }, requires: ['a'] },
      { id: 'c', mineral: 'south', rect: { x: 645, y: 485, w: 145, h: 20 }, requires: ['b'] },
      { id: 'd', mineral: 'west', rect: { x: 80, y: 275, w: 20, h: 120 }, requires: ['c'] },
    ],
    gates: [
      { id: 'east', rect: { x: 555, y: 85, w: 18, h: 105 }, requires: ['a'] },
      { id: 'west', rect: { x: 480, y: 375, w: 18, h: 115 }, requires: ['b', 'c'] },
      { id: 'high', rect: { x: 100, y: 245, w: 115, h: 18 }, requires: ['d'] },
    ],
  },
  {
    title: 'The long way home',
    lesson: 'A release can change your route even after its switch is lit.',
    hint: 'Complete the circuit, then use Mossjade once more to turn toward High.',
    hints: ['What route reaches the receiver after all four switches are powered?', 'The West and High refits extend the supply chain. Release Mossjade there to turn upward, even though A is already powered.', 'Start Skyglass + Mossjade and release Mossjade toward A. At Upper add Sunstone and release Skyglass toward B. At East add Ironroot and release Sunstone toward C. At Low add Mossjade and release Ironroot toward D. At West add Skyglass, then release Mossjade to turn upward to High. Keep Skyglass, add Sunstone, and take the diagonal to the receiver.'],
    docks: [
      { x: 480, y: 335, r: 32, name: 'Launch', minerals: ['north', 'west'] },
      { x: 365, y: 190, r: 42, name: 'Upper', minerals: ['east'] },
      { x: 650, y: 75, r: 40, name: 'East', minerals: ['south'] },
      { x: 765, y: 315, r: 40, name: 'Low', minerals: ['west'] },
      { x: 265, y: 430, r: 40, name: 'West', minerals: ['north'] },
      { x: 150, y: 160, r: 38, name: 'High', minerals: ['east'] },
      { x: 250, y: 60, r: 35, name: 'Receiver', exit: true },
    ],
    walls: [{ x: 550, y: 240, w: 110, h: 100 }],
    switches: [
      { id: 'a', mineral: 'west', rect: { x: 190, y: 170, w: 20, h: 130 } },
      { id: 'b', mineral: 'north', rect: { x: 430, y: 30, w: 145, h: 20 }, requires: ['a'] },
      { id: 'c', mineral: 'east', rect: { x: 890, y: 125, w: 20, h: 125 }, requires: ['b'] },
      { id: 'd', mineral: 'south', rect: { x: 575, y: 480, w: 150, h: 20 }, requires: ['c'] },
    ],
    gates: [
      { id: 'east', rect: { x: 535, y: 65, w: 18, h: 115 }, requires: ['a', 'b'] },
      { id: 'west', rect: { x: 495, y: 375, w: 18, h: 110 }, requires: ['c', 'd'] },
      { id: 'high', rect: { x: 100, y: 315, w: 115, h: 18 }, requires: ['d'] },
    ],
  },
  {
    title: 'Bring it back',
    lesson: 'Return with a mineral your starting dock cannot supply.',
    hint: 'The receiver route needs Sunstone brought back through the whole circuit.',
    hints: ['Which mineral is missing at Launch, and how can you bring it back?', 'The lower-right release is only a turn. D waits below the return route from High. Bring Sunstone from High back to Launch, then combine it with Skyglass.', 'Start Skyglass + Mossjade; release Mossjade toward A. Add Sunstone at Upper and release Skyglass toward B. Add Ironroot at East and release Sunstone toward C. Add Mossjade at Low, releasing Ironroot to turn left. Add Skyglass at West, releasing Mossjade to turn up. At High replace Skyglass with Ironroot and add Sunstone; release Ironroot toward D and ride right to Launch. Keep Sunstone, add Skyglass, then release Sunstone to turn upward to the receiver.'],
    docks: [
      { x: 480, y: 335, r: 42, name: 'Launch', minerals: ['north', 'west'] },
      { x: 365, y: 190, r: 42, name: 'Upper', minerals: ['east'] },
      { x: 650, y: 75, r: 40, name: 'East', minerals: ['south'] },
      { x: 765, y: 315, r: 40, name: 'Low', minerals: ['west'] },
      { x: 265, y: 430, r: 40, name: 'West', minerals: ['north'] },
      { x: 150, y: 160, r: 38, name: 'High', minerals: ['east', 'south'] },
      { x: 595, y: 160, r: 34, name: 'Receiver', exit: true },
    ],
    walls: [{ x: 550, y: 305, w: 110, h: 55 }],
    switches: [
      { id: 'a', mineral: 'west', rect: { x: 190, y: 170, w: 20, h: 130 } },
      { id: 'b', mineral: 'north', rect: { x: 430, y: 30, w: 145, h: 20 }, requires: ['a'] },
      { id: 'c', mineral: 'east', rect: { x: 890, y: 125, w: 20, h: 125 }, requires: ['b'] },
      { id: 'd', mineral: 'south', rect: { x: 275, y: 480, w: 150, h: 20 }, requires: ['a', 'b', 'c'] },
    ],
    gates: [
      { id: 'east', rect: { x: 535, y: 65, w: 18, h: 100 }, requires: ['a', 'b'] },
      { id: 'return', rect: { x: 430, y: 380, w: 18, h: 110 }, requires: ['c'] },
      { id: 'receiver', rect: { x: 545, y: 240, w: 110, h: 18 }, requires: ['a', 'b', 'c', 'd'] },
    ],
  },
];
